version: 2.1

orbs:
  heroku: circleci/heroku@0.0.10. # Invoke the Heroku orb
  node: circleci/node@2.0.2

workflows:
  matrix-tests:
    jobs:
      - node/test:
          version: 13.11.0
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - build
          filters:
            branches:
              only: sequential-branch-filter
